spring:
  application:
    name: ad-filters-subscriber
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 6 #警告阈值, 原始规则长度小于该值时会输出警告日志

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:
    #远程订阅规则 （！使用前请删除下方示例配置, 注意缩进）
    remote:
      - name: 'AdGuard 中文'
        path: 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt'

      - name: 'AdGuard DNS filter'
        path: 'https://raw.githubusercontent.com/AdguardTeam/HostlistsRegistry/main/assets/filter_1.txt'
      
      - name: 'anti-AD'
        path: 'https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt'
      
      - name: 'hagezi手动维护'
        path: 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/personal.txt'
      
      - name: '秋风'
        path: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt'
      
      - name: '大萌主'
        path: 'https://raw.githubusercontent.com/damengzhu/banad/main/dnslist.txt'
      
      - name: 'jerryn70-Xiaomi'
        path: 'https://hub.xjadh.link/https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Xiaomi-Extension.txt'
      
      - name: 'abp'
        path: 'https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt'
       
      - name: 'easylistchina'
        path: 'https://easylist-downloads.adblockplus.org/easylistchina.txt'
      
      - name: 'easyprivacy'
        path: 'https://easylist-downloads.adblockplus.org/easyprivacy.txt'
      
      - name: 'cjx-annoyance'
        path: 'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt'
      
      - name: 'i-dont-care-about-cookies'
        path: 'https://www.i-dont-care-about-cookies.eu/abp/'
      
      - name: '5whys-min'
        path: 'https://raw.githubusercontent.com/5whys-adblock/AdGuardHome-rules/main/rules/output_min.txt'
      
      - name: 'Cats-Team'
        path: 'https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt'
      
      - name: 'XXKiller'
        path: 'https://raw.githubusercontent.com/DoingDog/XXKiller/main/w.txt'
      
    #本地规则文件
    local:
      - name: 'local rule'
        path: 'local-rule.txt' #支持绝对/相对路径

  #输出配置
  output:
    #生成的规则文件头部内容, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
    file_header: |
      [ADFS Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/fordes123/ad-filters-subscriber/
      ! From: AdGuard anti-AD 秋风 大萌主 jerryn70 adblock cjx-annoyance i-dont-care-about-cookies
      ! From: 5whys Cats-Team XXKiller
    path: rule #输出规则文件的路径，支持绝对/相对路径
    #输出规则文件列表 （！注意缩进）
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则
        - MODIFY  #修饰规则，添加了一些修饰符号的规则
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
